core/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'communities', views.CommunityViewSet)
router.register(r'comments', views.CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-community/', views.CommunityCreate.as_view(), name='create-community'),
    path('communities/', views.communities_page, name='communities'),

    path('create-post/', views.PostCreate.as_view(), name='create-post'),
    path('<int:pk>/', views.show_post, name='post'),
    path('edit-post/<int:pk>/', views.PostEdit.as_view(), name='edit-post'),
    path('delete-post/<int:pk>', views.delete_post, name='delete-post'),

    path('comment/reply/', views.reply_comment, name='reply'),
    path('delete-comment/<int:pk>', views.delete_comment, name='delete-comment'),
]

micro_reddit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import home_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_page, name='home'),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('posts/', include('core.urls')),

    path('api-auth/', include('rest_framework.urls')),
    path('api/core/', include('core.api.urls')),
    path('api/users/', include('users.api.urls')),

    # path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.core.validators import MinLengthValidator
from django.urls import reverse
from users.models import User


class Community(models.Model):
    name = models.CharField(
        max_length=25,
        unique=True,
        blank=False,
        validators=[MinLengthValidator(3)],
        )
    description = models.TextField(blank=False)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Communities'

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.CASCADE,
        verbose_name='Choose a community',
        related_name='posts'
        )
    title = models.CharField(
        max_length=80,
        blank=False,
        validators=[MinLengthValidator(3)],
        )
    body = models.TextField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return reverse('post', kwargs={'id': self.id})

    def get_comments(self) -> QuerySet:
        """
        Return all top-level comments.
        Top-level means that comment
        is reply to post, not to other
        comment
        """
        return self.comments.filter(parent=None)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                               null=True, blank=True,
                               related_name='children')
    body = models.TextField(max_length=200, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self) -> str:
        return self.body[:20]

    def get_comments(self) -> QuerySet:
        """
        Return comments that are direct
        children to called Comment instance
        """
        return Comment.objects.filter(parent=self)

core/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].widget.attrs = {'placeholder': 'Comment here...'}

core/api/views.py
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from core.models import Post, Community, Comment
from . import serializers


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = serializers.PostSerializer
    pagination_class = PageNumberPagination


class CommunityViewSet(viewsets.ModelViewSet):
    queryset = Community.objects.all()
    serializer_class = serializers.CommunitySerializer
    pagination_class = PageNumberPagination


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = serializers.CommentSerializer
    pagination_class = PageNumberPagination

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from .models import Community, Post, Comment
from .forms import CommentForm


# Community Views

class CommunityCreate(LoginRequiredMixin, CreateView):
    redirect_field_name = 'next'

    model = Community
    fields = ['name', 'description']
    template_name = 'core/community_form.html'

    success_url = reverse_lazy('home')


def communities_page(request: HttpRequest) -> HttpResponse:
    query = request.GET.get('q', '')
    communities = Community.objects.filter(name__icontains=query)

    context = {'communities': communities}
    return render(request, 'core/communities_page.html', context)


# Post Views

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['community', 'title', 'body']
    template_name = 'core/post_form.html'
    success_url = reverse_lazy('home')

    redirect_field_name = 'next'

    def form_valid(self, form) -> HttpResponseRedirect:
        form.instance.user = self.request.user
        return super().form_valid(form)


def show_post(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, id=pk)
    post_top_level_comments = post.get_comments().select_related('user')
    post_comments_num = post.comments.count()

    # We allow users to comment on this post
    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.parent = None
            new_comment.save()
            return redirect(post.get_absolute_url()+'#comment-'+str(new_comment.id))

    context = {
        'post': post,
        'post_comments_num': post_comments_num,
        'comment_form': comment_form,
        'post_top_level_comments': post_top_level_comments,
        }

    return render(request, 'core/post_detail.html', context)


class PostEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']

    template_name = 'core/post_form.html'

    redirect_field_name = 'next'

    def get_success_url(self) -> str:
        return reverse('post', args=[self.object.id])

    def test_func(self) -> bool:
        post = self.get_object()
        return self.request.user == post.user


@login_required()
def delete_post(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, id=pk)

    if request.user != post.user:
        raise PermissionDenied()

    if request.method == 'POST':
        post.delete()
        return redirect('home')

    context = {'object': post}
    return render(request, 'delete.html', context)


# Comment Views

@login_required()
def reply_comment(request: HttpRequest) -> HttpResponseRedirect:
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            post_id = request.POST.get('post')
            post = Post.objects.get(id=post_id)
            parent_id = request.POST.get('parent')
            parent = Comment.objects.get(id=parent_id)
            user = request.user
            reply = form.save(commit=False)

            reply.post = post
            reply.parent = parent
            reply.user = user
            reply.save()

            return redirect(post.get_absolute_url()+'#comment-'+str(reply.id))


@login_required()
def delete_comment(request: HttpRequest, pk: int) -> HttpResponse:
    comment = get_object_or_404(Comment, id=pk)
    post = comment.post

    if request.user != comment.user:
        raise PermissionDenied()

    if request.method == 'POST':
        comment.delete()
        return redirect('post', post.id)

    context = {'object': comment}
    return render(request, 'delete.html', context)


# Common Views

def home_page(request: HttpRequest) -> HttpResponse:
    query = request.GET.get('q', '')
    page_number = request.GET.get('page', 1)
    number_of_posts = Post.objects.count()
    posts = Post.objects.filter(
        Q(community__name__icontains=query) |
        Q(title__icontains=query) |
        Q(body__icontains=query)
    ).prefetch_related('user', 'community', 'comments')

    paginator = Paginator(posts, per_page=10)

    try:
        page_object = paginator.get_page(page_number)
    # If page is not integer return 1st page
    except PageNotAnInteger:
        page_object = paginator.get_page(1)
    # If page is out of range return last page
    except EmptyPage:
        page_object = paginator.get_page(paginator.num_pages)

    communities = Community.objects.prefetch_related('posts')[:5]
    community_comments = Comment.objects.filter(
        Q(post__community__name__icontains=query)
    ).select_related('user', 'post')[:10]

    context = {
        'page_obj': page_object,
        'number_of_posts': number_of_posts,
        'communities': communities,
        'community_comments': community_comments,
        'query': query,
        }

    return render(request, 'home.html', context)

core/templates/core/activity_partial.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for comment in community_comments %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'profile' comment.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{ comment.user.avatar.url }}" />
          </div>
          <p>
            @{{comment.user.username}}
            <span>{{comment.created_at|timesince}} ago</span>
          </p>
        </a>
        {% if request.user == comment.user %}
          <div class="roomListRoom__actions">
          <a href="{% url 'delete-comment'  comment.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
            </svg>
          </a>
          </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'post' comment.post.id %}">{{comment.post}}</a>”</p>
        <div class="activities__boxRoomContent">
          {{comment.body}}
        </div>
      </div>
    </div>
  {% endfor %}
</div>

core/templates/core/comment_partial.html
<details open class="comment" id="comment-{{comment.id}}">
  <a href="#comment-{{comment.id}}" class="comment-border-link">
    <span class="sr-only">Jump to comment-{{comment.id}}</span>
  </a>
  <summary>
    <div class="comment-heading">
      <div class="thread__top">
        <div class="thread__author">
          <a href="{% url 'profile' comment.user.id %}" class="thread__authorInfo">
            <div class="avatar avatar--small">
              <img src="{{comment.user.avatar.url}}" />
            </div>
            <span>@{{comment.user.username}}</span>
          </a>
          <span class="thread__date">{{comment.created_at|timesince}} ago</span>
        </div>
        {% if request.user == comment.user %}
          <a href="{% url 'delete-comment' comment.id %}">
            <div class="thread__delete">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
              </svg>
            </div>
          </a>
        {% endif %}
        </div>
    </div>
  </summary>

  <div class="comment-body">
    <p>
      {{comment.body}}
    </p>
    <button type="button" data-toggle="reply-form" data-target="comment-{{comment.id}}-reply-form">Reply</button>
    <form method="POST" action="{% url 'reply' %}" class="reply-form d-none" id="comment-{{comment.id}}-reply-form">
      {% csrf_token %}
      <input type="hidden" name="post" value="{{post.id}}">
      <input type="hidden" name="parent" value="{{comment.id}}">
      {{comment_form.as_p}}
      <div>
        <button type="submit">Submit</button>
        <button type="button" data-toggle="reply-form" data-target="comment-{{comment.id}}-reply-form">Cancel</button>
      </div>
    </form>
  </div>

  <div class="replies">
    {% for comment in comment.get_comments %}
      {% include 'core/comment_partial.html' with comment=comment %}
    {% endfor %}
  </div>
</details>

core/templates/core/communities_page.html
{% extends 'base.html' %}

{% block content %}

<main class="layout layout--3">
  <div id="container-topics">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Browse Communities</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for communities" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'communities' %}" class="active">All</span></a>
          </li>
          {% for community in communities %}
            <li>
              <a href="{% url 'home' %}?q={{community.name}}">{{community.name}}<span>{{community.post_set.all.count}}</span></a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock %}

core/templates/core/communities_partial.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Communities</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'home' %}" class="active">All</a>
    </li>
    {% for community in communities %}
      <li>
        <a href="{% url 'home' %}?q={{community.name}}">{{community.name}}<span>{{community.posts.all.count}}</span></a>
      </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'communities' %}">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

core/templates/core/community_detail_partial.html
<div class="activities">
  <div class="activities__header">
    <h2>About Community</h2>
  </div>
  <div class="activities__box">
    <div class="community__boxHeader roomListRoom__header">
      <p>{{community.name}}</p>
    </div>
    <br/>
    <div class="activities__boxContent">
      <p>{{community.description}}</p>
      </br>
      <div class="activities__boxRoomContent">
        <p>Created at {{community.created_at}}</p>
      </div>
    </div>
  </div>
</div>

core/templates/core/community_form.html
{% extends 'base.html' %}

{% block content %}

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create community</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}

            {% if form.non_field_errors %}
              <ul class="error-message">{{ form.non_field_errors }}</ul>
            {% endif %}

            {% for field in form %}
              <div class="form__group">
                <label for="room_name">{{ field.label }}</label>
                {{ field }}
                <ul class="error-message">{{ field.errors }}</ul>
              </div>
            {% endfor %}

            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

core/templates/core/post_detail.html
{% extends 'base.html' %}

{% block content %}

<main class="profile-page layout layout--2">
  <div class="container">
    <div class="room">
      <div class="room__top">
        <div class="room__topLeft">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>r/{{post.community.name}}</h3>
        </div>
        {% if post.user == request.user %}
          <div class="room__topRight">
            <a href="{% url 'edit-post' post.id %}">
              <svg
                enable-background="new 0 0 24 24"
                height="32"
                viewBox="0 0 24 24"
                width="32"
                xmlns="http://www.w3.org/2000/svg"
              >
                <title>edit</title>
                <g>
                  <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                </g>
                <g>
                  <g>
                    <path
                      d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                    />
                  </g>
                  <g>
                    <path
                      d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                    />
                  </g>
                </g>
              </svg>
            </a>
            <a href="{% url 'delete-post' post.id %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
              </svg>
            </a>
          </div>
        {% endif %}
      </div>
      <div class="post_box">
        <div class="post_header">
          <div class="room__info">
            <h3>{{post.title}}</h3>
            <span>{{post.created_at|timesince}} ago</span>
          </div>
          <div class="room__hosted">
            <p>Posted By</p>
            <a href="{% url 'profile' post.user.id %}" class="room__author">
              <div class="avatar avatar--small">
                <img src="{{post.user.avatar.url}}" />
              </div>
              <span>@{{post.user.username}}</span>
            </a>
          </div>
          </br>
          <div class="room__details">
            {{post.body}}
          </div>
        </div>
        <div class="post_footer">
          {% if request.user.is_authenticated %}
            <p>Comment as <strong>{{request.user}}</strong></p>
            <div class="comment_form">
              <form action="" method="POST">
                {% csrf_token %}
                <input name="body" placeholder="What are your thoughts?..." />
                <button type="submit" class="">Comment</button>
              </form>
            </div>
          {% endif %}
        </div>
        {% with comments.count as total_comments %}
          <h1 class="comments_section_header">
            <strong>
            {{ post_comments_num }} comment{{ post_comments_num|pluralize }}
            </strong>
          </h1>
        {% endwith %}
        <div class="comment-thread">
          {% for comment in post_top_level_comments %}
            {% include 'core/comment_partial.html' %}
          {% endfor %}
        </div>
      </div>
    </div>
    {% include 'core/community_detail_partial.html' with community=post.community %}
  </div>
</main>

{% endblock %}

core/templates/core/post_form.html
{% extends 'base.html' %}

{% block content %}

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create or update post</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}

            {% if form.non_field_errors %}
              <ul class="error-message">{{ form.non_field_errors }}</ul>
            {% endif %}

            {% for field in form %}
              <div class="form__group">
                <label for="room_name">{{ field.label }}</label>
                {{ field }}
                <ul class="error-message">{{ field.errors }}</ul>
              </div>
            {% endfor %}

            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

core/templates/core/posts_partial.html
{% for post in posts %}
  <div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'profile' post.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{post.user.avatar.url}}" />
        </div>
        <span>@{{post.user.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{post.created_at|timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'post' post.id %}">{{post.title}}</a>
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'post' post.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>user-group</title>
        <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
        </svg>
        {{post.comments.all.count}} comments
      </a>
      <p class="roomListRoom__topic">{{post.community.name}}</p>
    </div>
  </div>
{% endfor %}